Repository operate-first/common, pull requests merged in 2021-07, with the labels that each got.

#3 Added Michal Drla (mimotej) to contributors.
  github-config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#4 Adding my Github handle to the member list
  github-config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#5 Cruft entries from changes during review
  labels.yaml
Labels: approved, lgtm, size/S

#8 feat: Add assign-to-oncall bot label
  labels.yaml
Labels: approved, lgtm, size/XS

#7 feat: Add community-handbook repo
  github-config.yaml
Labels: do-not-merge/hold, size/S

#12 Adding user Leihao Chen (Aaaaazzaa)
  github-config.yaml
Labels: approved, lgtm, size/XS
