Repository operate-first/common, pull requests merged in 2021-09, with the labels that each got.

#19 Added Surya Prakash Pathak (suppathak) to contributors
  github-config.yaml
Labels: lgtm, approved

#21 feat: Remove Aaaaazzaa user which no longer exists
  github-config.yaml
Labels: size/XS, lgtm, approved

#24 Updated github-config.yaml. Added neu students names to the contributors list.
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#25 add schwesig
  github-config.yaml
Labels: size/XS, lgtm, approved

#26 added my userId into the member list.
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#27 Remove duplicate user in contributors-core.
  github-config.yaml
Labels: size/XS, lgtm, approved

#28 Convert core contrib to triage and cleanup triager team.
  github-config.yaml
Labels: lgtm, size/S, approved

#30 Add operate-first user.
  github-config.yaml
Labels: size/XS, lgtm

#10 Labels docs patch 02
  labels.md
  labels.md.tmpl
Labels: lgtm, size/S, approved

#31 Add Pep to the operate-first org
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#29 Team DevSecOps to look after the CI
  github-config.yaml
Labels: lgtm, size/S, approved
