Repository operate-first/common, pull requests merged in 2021-12, with the labels that each got.

#49 Add new members to org.
  github-config.yaml
Labels: size/XS, lgtm

#50 Adding new members for sre-apprenticeship work
  github-config.yaml
Labels: size/XS, lgtm

#48 Added msdisme to orgs.operate-first.members
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#51 Added new `training` repo
  github-config.yaml
Labels: size/XS, lgtm, approved
