Repository operate-first/common, pull requests merged in 2022-08, with the labels that each got.

#138 add andreaTP, remove craicoverflow from apicurio
  github-config.yaml
Labels: size/XS

#139 Adding a new github id to github-config.yaml.
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#140 Make larsks a member of SourceOps team
  github-config.yaml
Labels: size/XS, lgtm, approved

#141 :pray: Thank you for your service
  OWNERS
  github-config.yaml
Labels: size/M, lgtm, approved

#143 Add OKD Working Group members to op1st GH org
  github-config.yaml
Labels: lgtm, size/S, approved, ok-to-test

#145 housekeeping, removing stale members to test prow permissions
  github-config.yaml
Labels: size/XS, lgtm, approved
