Repository operate-first/common, pull requests merged in 2022-02, with the labels that each got.

#62 Add training github team.
  github-config.yaml
Labels: size/XS

#66 Add Samuel to operate-first community
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#64 Rename sre repo to operations.
  github-config.yaml
Labels: lgtm, size/S

#67 add schwesig to OWNERS
  OWNERS
Labels: lgtm, size/S, approved

#68 New SRE repo
  github-config.yaml
Labels: size/XS, lgtm, approved

#65 AI for cloud operations
  github-config.yaml
Labels: size/M, lgtm, approved

#69 Add myself in Operate First members
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#73 :exclamation: Peribolos binaries is shifted to /ko-app/ dir
  .prow.yaml
Labels: size/XS, lgtm, approved

#71 Update github-config.yaml
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#74 Added timflannagan to the Curator team
  github-config.yaml
Labels: size/XS, lgtm
