Repository operate-first/common, pull requests merged in 2022-03, with the labels that each got.

#75 Add more odh members and make them odh-manifests admins.
  github-config.yaml
Labels: size/XS, lgtm, approved

#77 Give admin access to common repo to devsecops team
  .pre-commit-config.yaml
  github-config.yaml
Labels: size/XS, lgtm, approved

#76 Add myself @stefwalter as a member of Operate First
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#78 Fix label sync image binary
  .prow.yaml
Labels: size/XS, lgtm, approved

#80 creating the repo for IONOS OpenShift
  github-config.yaml
Labels: size/S

#81 Updating labels.yaml with a label for each cluster
  labels.yaml
Labels: size/M, lgtm, approved

#82 fybrik working group owners
  github-config.yaml
Labels: size/XS, lgtm, approved
