Repository operate-first/common, pull requests merged in 2022-07, with the labels that each got.

#134 Include jingyu for access to clusters
  github-config.yaml
Labels: size/XS, lgtm

#133 Add VannTen (Max Gautier) as project member
  github-config.yaml
Labels: size/XS, needs-ok-to-test

#135 feat: Add robozome repo
  github-config.yaml
Labels: size/XS, lgtm, approved

#136 Add permissions for mknell@redhat (uffish)
  github-config.yaml
Labels: size/XS, lgtm, approved, kind/website, area/contributor, sig/community

#137 Add OSC LF contributors.
  github-config.yaml
Labels: size/XS, lgtm
