Repository operate-first/common, pull requests merged in 2022-10, with the labels that each got.

#153 Update github-config.yaml
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#154 Adding Kristi Nikolla to Op1st org
  github-config.yaml
Labels: size/XS, lgtm, approved

#155 Add kepler team and edge demo repo.
  github-config.yaml
Labels: lgtm, size/S
