Repository operate-first/common, pull requests merged in 2022-05, with the labels that each got.

#105 Add mpeters as member of operate-first group
  github-config.yaml
Labels: size/XS, needs-ok-to-test

#107 Add team apicurio to operate-first org
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#109 Add dastergon to the org
  github-config.yaml
Labels: size/XS, lgtm, approved

#108 move_operate-first.github.io-to-old
  github-config.yaml
Labels: size/XS, lgtm, approved

#113 Add Dom Finn to org
  github-config.yaml
Labels: size/XS, lgtm, approved

#112 Forgot to create maintainers for the blog
  github-config.yaml
Labels: lgtm, size/S, approved

#114 Adding AvRajath to the Curator GitHub team
  github-config.yaml
Labels: size/XS, lgtm, approved

#111 Add jpweiser to orgs.operate-first.members
  github-config.yaml
Labels: size/XS, needs-ok-to-test
