Repository operate-first/common, pull requests merged in 2022-06, with the labels that each got.

#119 added github handle to github-config.yaml
  github-config.yaml
Labels: size/XS, needs-ok-to-test

#122 Update github-config.yaml
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#121 Update github-config.yaml
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#118 Creating group to maintain project websites
  github-config.yaml
Labels: lgtm, size/S, approved, ok-to-test

#124 fix: website maintainers invalid config
  github-config.yaml
Labels: size/XS, lgtm

#125 fix: sre-u has no main branch
  github-config.yaml
Labels: size/XS, approved

#106 add jbrooks
  github-config.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#126 Added GH id
  github-config.yaml
Labels: size/XS, needs-ok-to-test

#127 chore(service-catalog): Add catalog repo
  github-config.yaml
Labels: size/XS, lgtm, approved

#128 Add two members of RH's SIG SRE team
  github-config.yaml
Labels: size/XS, lgtm, approved

#130 adding schwesig to admin
  github-config.yaml
Labels: size/XS, lgtm, approved

#131 Added abirami-dhayalan to members
  github-config.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#132 feat: Relocate Probot repositories to Operate First
  github-config.yaml
  labels.md
  labels.yaml
Labels: size/M, lgtm, approved
